# gen-doc ODM.yaml --directory ./docs2 --hierarchical-class-view 

site_name: DataExchange-ODM-LinkML
site_url: https://cdisc-org.github.io/DataExchange-ODM-LinkML
repo_url: https://github.com/cdisc-org/DataExchange-ODM-Linkml

site_dir: '../cdisc-org.github.io'
docs_dir: './docs'

theme:
  name: "material"
  features:
    - content.tabs.link

plugins:
    - search
    - mermaid2

nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md